name: ATM MQ Demo

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --filter MessageServiceTests --no-restore --verbosity normal    
    - name: Artifactory Generate
      run: |
        dotnet publish ./ATM.MQ.Backend/ATM.MQ.Backend.csproj --output ./ATM.MQ.BackendPublish --configuration Release --no-build        
        dotnet publish ./ATM.MQ.Terminal/ATM.MQ.Terminal.csproj --output ./ATM.MQ.TerminalPublish --configuration Release --no-build    
    - name: Upload Backend Artifacts
      uses: actions/upload-artifact@v2      
      with: 
        name: ATM.MQ.BackendPublish
        path: ./ATM.MQ.BackendPublish                               
    - name: Upload Terminal Artifacts
      uses: actions/upload-artifact@v2      
      with: 
        name: ATM.MQ.TerminalPublish
        path: ./ATM.MQ.TerminalPublish
                       
  deploy:
    runs-on: ubuntu-latest    
    needs: build
    steps:
      - name: Deploy on GCP App Engine
        run: echo "Sending artifacts to GCP" 
      - name: Deploy on Azure
        run: echo "Sending artifacts to Azure"       
      - name: Deploy on AWS
        run: echo "Sending artifacts to AWS"         
